@startuml
' Common set of logos for system architecture diagrams.
!include <logos/azure>
!include <logos/amex>
!include <logos/android>
!include <logos/angular>
!include <logos/apache>
!include <logos/apple>
!include <logos/aws>
!include <logos/blueprint>
!include <logos/box>
!include <logos/c-sharp>
!include <logos/compass>
!include <logos/d3>
!include <logos/debian>
!include <logos/deploy>
!include <logos/desk>
!include <logos/docker>
!include <logos/dotnet>
!include <logos/dropbox>
!include <logos/electron>
!include <logos/facebook>
!include <logos/firefox>
!include <logos/flow>
!include <logos/font-awesome>
!include <logos/fsharp>
!include <logos/git>
!include <logos/github>
!include <logos/google-cloud>
!include <logos/google-drive>
!include <logos/google-gmail>
!include <logos/google-gsuite>
!include <logos/google-icon>
!include <logos/google>
!include <logos/gulp>
!include <logos/hadoop>
!include <logos/instagram-icon>
!include <logos/java>
!include <logos/javascript>
!include <logos/jekyll>
!include <logos/jenkins>
!include <logos/jira>
!include <logos/jquery>
!include <logos/json>
!include <logos/kubernetes>
!include <logos/linkedin>
!include <logos/macOS>
!include <logos/mailchimp>
!include <logos/markdown>
!include <logos/microsoft-edge>
!include <logos/microsoft-windows>
!include <logos/microsoft>
!include <logos/mock-server>
!include <logos/mono>
!include <logos/mozilla>
!include <logos/mysql>
!include <logos/modejs>
!include <logos/npm>
!include <logos/oauth>
!include <logos/opensource>
!include <logos/oracle>
!include <logos/parse>
!include <logos/paypal>
!include <logos/perl>
!include <logos/php>
!include <logos/pinterest>
!include <logos/postman>
!include <logos/python>
!include <logos/pytorch>
!include <logos/pyup>
!include <logos/rackspace>
!include <logos/raspberry-pi>
!include <logos/react>
!include <logos/reddit>
!include <logos/redhat>
!include <logos/redis>
!include <logos/redux>
!include <logos/rest>
!include <logos/rsa>
!include <logos/ruby>
!include <logos/safari>
!include <logos/salesforce>
!include <logos/selenium>
!include <logos/sendgrid>
!include <logos/serverless>
!include <logos/signal>
!include <logos/skype>
!include <logos/slack>
!include <logos/stackoverflow>
!include <logos/stoplight>
!include <logos/stripe>
@enduml
